config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :rides, only: %i[index new show create edit update destroy] do
    resources :bookings, only: %i[create]
    resources :chatrooms, only: :create
  end

  resources :chatrooms, only: %i[index show] do
    resources :messages, only: %i[create]
  end

  resources :bookings, only: %i[show update] do
    resources :reviews, only: %i[new create]
    resources :payments, only: :new
  end

  get '/beach/:id', to: 'rides#beach', as: "beach"
  get '/location/:id', to: 'rides#location', as: "location"
  get '/dashboard', to: 'pages#dashboard'
  get '/landing', to: 'pages#home'
  get '/profile', to: 'pages#profile'
  get '/bookings/:id/confirmation', to: 'bookings#booking_confirmation', as: "confirmation"

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :beaches, only: [] do
    member do
      get :favorite
    end
  end
end

app/views/shared/_back_btn.html.erb
<%= link_to :back, class:"no-text-decoration" do %>
  <div class="d-flex justify-content-center align-items-center btn-back">
    <i class="fa-solid fa-caret-left"></i>
  </div>
<% end %>

app/views/shared/_curvo.html.erb
<div class="main">
  <div class="wrapper">
    <div class="box"></div>
    <div class="position-absolute d-flex align-items-center top-div">
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">
        <span><i class="fa-solid fa-bars"></i></span>
      </button>
      <h4 class="profile-name"><%= current_user.full_name %></h4>
    </div>
  </div>
</div>

<div class="offcanvas offcanvas-start slide-menu" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasExampleLabel">
  <div class="offcanvas-header flex-row-reverse">
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <div class="mt-3">
      <ul class="slide-menu-items">
        <li><%= link_to "My dashboard", dashboard_path, class: "dropdown-item" %></li>
        <li><%= link_to "Messages", chatrooms_path, class: "dropdown-item" %></li>
        <li><%= link_to "Create new ride", new_ride_path, class: "dropdown-item" %></li>
        <li><%= button_to "Sign out", destroy_user_session_path, method: :delete, data:{ turbo: :false }, class: "dropdown-item" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_heart_btn.html.erb
<%= link_to favorite_beach_path(date: params[:date]), class:"no-text-decoration", id: "favorite_btn_#{dom_id(beach)}" do %>
  <div class="d-flex justify-content-center align-items-center btn-heart">
    <i class="fa-<%= current_user.favorited?(beach) ? 'solid' : 'regular' %> fa-heart"></i>
  </div>
<% end %>

app/views/shared/_message_nav.html.erb
<nav class="navbar bg-transparent position-absolute w-100">
  <div class="container-fluid">
    <%= link_to :back, class:"no-text-decoration" do %><i class="fa-solid fa-caret-left back-message"></i><% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <span><i class="fa-solid fa-bars bars-message"></i></span>
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body text-end" style="y-index: +2;">
        <div class="mt-3">
          <ul class="right-slide-menu-items">
            <% if user_signed_in? %>
              <div class="username">
                <%= current_user.full_name %>
              </div>
              <li><%= link_to "My dashboard", dashboard_path, class: "dropdown-item" %></li>
              <li><%= link_to "My profile", profile_path, class: "dropdown-item" %></li>
              <li><%= link_to "Messages", chatrooms_path, class: "dropdown-item" %></li>
              <li><%= link_to "Create new ride", new_ride_path, class: "dropdown-item" %></li>
              <li><%= button_to "Sign out", destroy_user_session_path, method: :delete, data:{ turbo: :false }, class: "dropdown-item" %></li>
            <% else %>
              <li><%= link_to "Sign in", new_user_session_path, class: "dropdown-item" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-light navbar-lewagon" id="top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", class: "logo" %>
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <p class="brand">Tag Along</p>
          <p class="nav-link"><span data-controller="typed-js"></span></p>
        </li>
      </ul>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">
      <span class="navbar-toggler-icon hide-large"></span>
      <% if user_signed_in? %>
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle hide-small", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= link_to "Sign in", "#", class: "hide-small btn-blue-navbar" %>
          <%= image_tag "user.png", class: "avatar dropdown-toggle hide-small", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>

      <% end %>
    </button>
    <div class="offcanvas offcanvas-end align-items-end" data-bs-backdrop="false" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
      <div class="offcanvas-header">
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body text-end">
        <div class="mt-3">
          <ul class="right-slide-menu-items">
            <% if user_signed_in? %>
              <div class="username">
                <%= current_user.full_name %>
              </div>
              <li><%= link_to "My dashboard", dashboard_path, class: "dropdown-item" %></li>
              <li><%= link_to "My profile", profile_path, class: "dropdown-item" %></li>
              <li><%= link_to "Messages", chatrooms_path, class: "dropdown-item" %></li>
              <li><%= link_to "Create new ride", new_ride_path, class: "dropdown-item" %></li>
              <li><%= button_to "Sign out", destroy_user_session_path, method: :delete, data:{ turbo: :false }, class: "dropdown-item" %></li>
            <% else %>
              <li><%= link_to "Sign in", new_user_session_path, class: "dropdown-item" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_simple_nav.html.erb
<nav class="navbar bg-transparent position-absolute w-100" style="z-index: +1;">
  <div class="container-fluid">
    <%= link_to :back, class:"no-text-decoration" do %><i class="fa-solid fa-caret-left back-arw"></i><% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <span><i class="fa-solid fa-bars bars-simple"></i></span>
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body text-end">
        <div class="mt-3">
          <ul class="right-slide-menu-items">
            <% if user_signed_in? %>
              <div class="username">
                <%= current_user.full_name %>
              </div>
              <li><%= link_to "My dashboard", dashboard_path, class: "dropdown-item" %></li>
              <li><%= link_to "My profile", profile_path, class: "dropdown-item" %></li>
              <li><%= link_to "Messages", chatrooms_path, class: "dropdown-item" %></li>
              <li><%= link_to "Create new ride", new_ride_path, class: "dropdown-item" %></li>
              <li><%= button_to "Sign out", destroy_user_session_path, method: :delete, data:{ turbo: :false }, class: "dropdown-item" %></li>
            <% else %>
              <li><%= link_to "Sign in", new_user_session_path, class: "dropdown-item" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>