config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :rides, only: %i[index new show create edit update destroy] do
    resources :bookings, only: %i[create]
    resources :chatrooms, only: :create
  end

  resources :chatrooms, only: %i[index show] do
    resources :messages, only: %i[create]
  end

  resources :bookings, only: %i[show update] do
    resources :reviews, only: %i[new create]
    resources :payments, only: :new
  end

  get '/beach/:id', to: 'rides#beach', as: "beach"
  get '/location/:id', to: 'rides#location', as: "location"
  get '/dashboard', to: 'pages#dashboard'
  get '/landing', to: 'pages#home'
  get '/profile', to: 'pages#profile'
  get '/bookings/:id/confirmation', to: 'bookings#booking_confirmation', as: "confirmation"

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :beaches, only: [] do
    member do
      get :favorite
    end
  end
end

app/views/pages/_beach_card.html.erb
<%= link_to beach_path(beach, date: @date), class:"no-text-decoration" do %>
  <div class="location-card me-3"
  style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.3)), url('<%= cl_image_path beach.photo.key %>')"
  data-controller="wheather-api"
  data-wheather-api-lat-value="<%= beach.latitude %>"
  data-wheather-api-long-value="<%= beach.longitude %>"
  data-wheather-api-api-key-value="<%= ENV['STORMGLASS_API_KEY'] %>">
    <h1 class="absolute beach-name" style="white-space: pre-wrap;"><%= beach.name %></h1>
    <div class="d-flex absolute rides-tag"><p class="zero-bottom">Rides: <%= beach.rides.on_date(@date).count %></p></div>
    <div class="contidions-container">
      <div class="wind-container">
        <p class="condition-stat"><i class="fa-solid fa-wind"></i></p>
        <p class="condition-stat ms-2" data-wheather-api-target="windspeed"></p>
        <p class="condition-stat">m/s</p>
        <p class="condition-stat ms-2" data-wheather-api-target="winddirection"></p>
      </div>
      <div class="wave-container">
        <p class="condition-stat"><i class="fa-solid fa-water"></i></p>
        <p class="condition-stat ms-2" data-wheather-api-target="waveheight"></p>
        <p class="condition-stat">m</p>
      </div>
    </div>
    <h3 class="absolute beach-location"><i class="fa-solid fa-location-dot"></i> <%= beach.location.name %></h3>
  </div>
<% end %>

app/views/pages/_booking_card.html.erb
<%= link_to booking_path(booking), class:"no-text-decoration", data: { turbo: false }  do %>
  <div class="booking-card mb-3 position-relative">
    <div class="position-absolute" style="top: 16px; right: 0;">
      <% if booking.state == "pending" %>
        <div style="background-color: #FF8552; padding: 5px 15px; color: white; border-radius: 20px 0 0 20px;">
          <p style="margin-bottom: 0;"><%= booking.state %></p>
        </div>
      <% else %>
        <div style="background-color: #1e9949; padding: 5px 15px; color: white; border-radius: 20px 0 0 20px;">
          <p style="margin-bottom: 0;"><%= booking.state %></p>
        </div>
      <% end %>
    </div>
    <div class="d-flex">
      <div class="img-ride-card d-flex justify-content-center align-items-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path booking.ride.beach.photo.key %>);">
          <div style="text-align: center;">
            <h1 style="font-size: 20px;"><%= booking.ride.beach.name %></h1>
          </div>
      </div>
      <div style="width: 50%;" class="mt-3">
        <div class="d-flex justify-content-between">
        </div>
        <div class="d-flex">
          <p class="card-date" style="margin-bottom: 5px;"><i class="fa-solid fa-clock"></i> <%= booking.ride.date_time.strftime("%H:%M") %></p>
        </div>
        <div class="d-flex justify-content-between">
          <div class="card-location-infos">
            <p style="margin-bottom: 5px;">Pick up:</p>
            <p style="font-size: 14px; margin-bottom: 0;"><i class="fa-sharp fa-solid fa-location-dot" style="color: #61D8EF;"></i> <%= booking.ride.address.match(/^[^,]+(?=,)/) %></p>
            <p style="font-size: 14px; padding-left: 14px;"><%= booking.ride.city %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/pages/_location_card.html.erb
<%= link_to location_path(location, date: @date) do %>
  <% if location.photo.present? %>
    <div class="location-card me-3" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.3)), url('<%= cl_image_path location.photo.key %>')">
      <h1 class="absolute name zero-bottom"><%= location.name %></h1>
      <div class="d-flex absolute rides-tag">
        <p class="zero-bottom">Rides: <%= location.rides.on_date(@date).count %></p>
      </div>
    </div>
  <% else  %>
    <div class="location-card me-3" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.3)), url('<%= image_path 'background.jpg' %>')">
      <h1 class="absolute name zero-bottom"><%= location.name %></h1>
      <div class="d-flex absolute rides-tag">
        <p class="zero-bottom">Rides: <%= location.rides.count %></p>
      </div>
    </div>
    <% end %>
<% end %>

app/views/pages/_ride_card.html.erb
<%= link_to ride_path(ride), class:"no-text-decoration" do %>
  <div class="booking-card mb-3">
    <div class="d-flex">
      <div class="img-ride-card d-flex justify-content-center align-items-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path ride.beach.photo.key %>);">
          <div style="margin: 0 10px; text-align: center;">
            <h1 style="font-size: 20px; margin-bottom: 0;"><%= ride.beach.name %></h1>
          </div>
      </div>
      <div style="width: 50%;" class="mt-3">
        <div class="d-flex justify-content-between">
        </div>

        <div class="d-flex justify-content-between position-relative">
          <div class="d-flex align-items-center position-absolute" style="top: 5px; right: 28px;">
            <p class="card-date" style="margin-bottom: 5px;"><i class="fa-solid fa-clock"></i> <%= ride.date_time.strftime("%H:%M") %></p>
          </div>
          <div class="card-location-infos">
            <div class="d-flex justify-content-between" style="width: 100%;">
              <p style="margin-bottom: 5px;">Pick up:</p>
            </div>
            <p style="font-size: 14px; margin-bottom: 0;"><i class="fa-sharp fa-solid fa-location-dot" style="color: #61D8EF;"></i> <%= ride.address.match(/^[^,]+(?=,)/) %></p>
            <p style="font-size: 14px; padding-left: 14px;"><%= ride.city %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/pages/dashboard.html.erb
<div class="dashboard" data-controller="dashboard-date">
  <div class="mt-5">
    <div class="d-flex justify-content-center">
      <i class="fa-solid fa-magnifying-glass me-2"></i>
      <form action="/dashboard" method="get" data-dashboard-date-target="form">
        <input type="date" name="date" class="mb-2" style="border: none; background-color: transparent;" data-dashboard-date-target="date" value="<%= @date %>">
      </form>
      <%# <p style="margin-bottom: 0;">When do you want to surf?</p> %>
    </div>
    <div class="d-flex justify-content-center">
      <hr style="width: 70%; color: #61D8EF; margin-top: 0;">
    </div>
  </div>

  <div class="container">
    <h1 class="mt-3">Beaches near you</h1>

    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="popular-tab" data-bs-toggle="tab" data-bs-target="#popular" type="button" role="tab" aria-controls="home" aria-selected="true">Popular</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="favourites-tab" data-bs-toggle="tab" data-bs-target="#favourites" type="button" role="tab" aria-controls="profile" aria-selected="false">Favorites</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="locations-tab" data-bs-toggle="tab" data-bs-target="#locations" type="button" role="tab" aria-controls="profile" aria-selected="false">Locations</button>
      </li>
    </ul>
    <div class="tab-content mt-3" id="myTabContent">
      <div class="scroll tab-pane fade show active" id="popular" role="tabpanel" aria-labelledby="popular-tab">
        <div data-dashboard-date-target="addUrl" data-url="/next_page?date=<%= @date %>">
          <div class="d-flex">
            <% @popular.each do |beach| %>
              <%= render "beach_card", beach: beach, date: @date %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="scroll tab-pane fade" id="favourites" role="tabpanel" aria-labelledby="favourites-tab">

        <div data-dashboard-date-target="addUrl">
          <div class="d-flex" style="white-space: nowrap;">
            <% @favorites.each do |beach| %>
              <%= render "beach_card", beach: beach %>
            <% end %>
          </div>
        </div>

      </div>
      <div class="scroll tab-pane fade" id="locations" role="tabpanel" aria-labelledby="locations-tab">
        <div data-dashboard-date-target="addUrl">
          <div class="d-flex">
            <% @locations.each do |location| %>
              <%= render "location_card", location: location %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <h1 class="mt-5 mb-3">Bookings</h1>
    <div>
      <% @bookings.each do |booking| %>
        <%= render "booking_card", booking: booking %>
      <% end %>
    </div>

    <% unless @user_rides.empty? %>
      <h1 class="mt-5 mb-3">Your Rides</h1>
      <% @user_rides.each do |ride| %>
        <%= render "ride_card", ride: ride %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-background">
  <div>
    <h3 class="home-header">Don't have a car? Not familiar with the nearby surfspots? No problem, TAG ALONG with surfers in your area!</h3>
  </div>
    <div class="form" data-controller="address-autocomplete" data-address-autocomplete-api-key-value="<%= ENV["MAPBOX_API_KEY"] %>">
      <%= simple_form_for :search, url: rides_path, method: "GET", html: { class: 'form-inline d-flex' } do |f| %>
      <%= f.input :address, as: :hidden, input_html: {data: {address_autocomplete_target: "address"}}, label: false %>
      <%= f.input :location, collection: Location::NAMES, label: false, prompt: "Drop off", class: "form-box" %>
      <div class="small-screen-inline">
        <%= f.input :date_time, as: :date, html5: true, label: false, wrapper_html: { class: "flex-grow-1" } %>
        <%= f.input :seats, collection: 1..5, label: false, prompt: "👤" %>
      </div>
      <%= f.submit "Search", class: "btn-search" %>
      <% end %>
    </div>
    <div class="text-white" data-controller="scroll-into">
        <%= image_tag "logo.png", class: "logo-home", data: {action: "click->scroll-into#scrollInto"}, title: "About us"%>
    </div>
</div>
<div class="about-container" id="info">
  <strong class="text-center text-white pt-4">About Tag Along</strong>
  <div class="about-text py-3">
    <p>Have you ever gone on a surf trip, only to arrive in the place and realize that the surf spots are way beyond walking distance from your hotel? Have you ever seen the swell of the season pass you by, while you are stuck at home without a ride? How about being new in town and have no one to surf with? Tag Along is the answer to all these concerns. Invented to connect surfers, improve wave accessibility and make surfing more sustainable by sharing rides. Surfers are social beings. Imagine catching the wave of your life, getting barrelled or having a gnarly wipeout if no one is there to see it. Tag Along allows surfers to catch a ride to the beach with other surfers, or to offer a ride. In the app you can navigate through the surf spots of your area and join</p>
  </div>
</div>

app/views/pages/profile.html.erb
<% if current_user.photo.attached? %>
  <%= cl_image_tag current_user.photo.key, class: "avatar-profile" %>
<% else %>
  <%= image_tag "user.png", class: "avatar-profile" %>
<% end %>

<div class="d-flex flex-row-reverse edit-position">
  <%= link_to edit_user_registration_path, class: "edit-link" do %>
  <div class="container">
    <div class="row">
      <div class="col-3">
        <i class="fa-solid fa-brush"></i>
      </div>
      <div class="col-9">
        <p class="edit">edit</p>
      </div>
    </div>
  </div>
  <% end %>
</div>

<div class="profile-main d-flex flex-column">
  <div class="d-flex justify-content-between mx-5 my-3">
    <div class="profile-icon"><i class="fa-solid fa-location-dot"></i></div>
    <strong class="my-2 profile-info"><%= current_user.city %></strong>
  </div>
  <div class="d-flex justify-content-between mx-5 my-3">
    <div class="profile-icon"><i class="fa-solid fa-car"></i></div>
    <strong class="my-2 profile-info"><%= current_user.car %></strong>
  </div>
  <div class="d-flex justify-content-between mx-5 my-3">
    <div class="profile-icon"><i class="fa-solid fa-pencil"></i></div>
    <p class="my-2 profile-info bio"><%= current_user.bio %></p>
  </div>
  <div class="d-flex justify-content-between mx-5 my-3">
    <div class="profile-icon"><i class="fa-solid fa-star"></i></div>
    <strong class="my-2 profile-info">Reviews</strong>
  </div>
</div>
<div class="reviews-div mx-4">
  <% current_user.reviews.each do |review| %>
    <div class="d-flex justify-content-around">
      <strong><%= review.booking.user.full_name %></strong>
      <span class="name-rating"><%= review.rating %><i class="fa-solid fa-star"></i></span>
    </div>
    <div class="mt-2 mb-5"><%= review.content %></div>
  <% end %>
</div>