config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :rides, only: %i[index new show create edit update destroy] do
    resources :bookings, only: %i[create]
    resources :chatrooms, only: :create
  end

  resources :chatrooms, only: %i[index show] do
    resources :messages, only: %i[create]
  end

  resources :bookings, only: %i[show update] do
    resources :reviews, only: %i[new create]
    resources :payments, only: :new
  end

  get '/beach/:id', to: 'rides#beach', as: "beach"
  get '/location/:id', to: 'rides#location', as: "location"
  get '/dashboard', to: 'pages#dashboard'
  get '/landing', to: 'pages#home'
  get '/profile', to: 'pages#profile'
  get '/bookings/:id/confirmation', to: 'bookings#booking_confirmation', as: "confirmation"

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :beaches, only: [] do
    member do
      get :favorite
    end
  end
end

app/models/ride.rb
class Ride < ApplicationRecord

  belongs_to :user
  belongs_to :beach
  has_many :bookings
  has_many :reviews, through: :bookings

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  delegate :location, to: :beach

  validates :date_time, :price_cents, :address, :seats, presence: true

  monetize :price_cents
  ## delegate is equal to the code below
  # def location
  #   beach.location
  # end

  reverse_geocoded_by :latitude, :longitude do |obj, results|
    if geo = results.first
      obj.city = geo.city
    end
  end

  after_validation :reverse_geocode

  scope :today, -> { where(date_time: Date.current.all_day) } # Ride.today
  scope :on_date, ->(date) { where(date_time: Date.parse(date).all_day) }

end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @search = params[:search]

    if @search.nil?
      @rides = Ride.all
    else
      @rides = RideSearch.new(params).search(Ride.all)
    end
  end

  def beach
    @date = params[:date] || Date.today.strftime("%Y-%m-%d")
    @beach = Beach.find(params[:id])
    @rides = Ride.where(beach: @beach).on_date(@date)
  end

  def location
    @date = params[:date] || Date.today.strftime("%Y-%m-%d")
    @location = Location.find(params[:id])
    @rides = @location.rides.on_date(@date)
  end

  def new
    @ride = Ride.new
  end

  def create
    @ride = Ride.new(ride_params)
    @ride.user = current_user
    if @ride.save
      redirect_to dashboard_path #this will be redirected to the user dashboard
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @ride = Ride.find(params[:id])
    @booking = Booking.new
    @markers = [{
      lat: @ride.latitude,
      lng: @ride.longitude
    },
    {
      lat: @ride.beach.latitude,
      lng: @ride.beach.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: {beach: @ride.beach})
    }]
  end

  def edit
    @ride = Ride.find(params[:id])
    @ride.date_time = nil
  end

  def update
    @ride = Ride.find(params[:id])
    @ride.update(ride_params)

    redirect_to ride_path(@ride)
  end

  private

  def ride_params
    params.require(:ride).permit(:beach_id, :seats, :price, :address, :date_time)
  end
end

app/views/rides/_info_window.html.erb
  <h2><%= beach.name %></h2>
  <p><%= beach.address %></p>

app/views/rides/_ride_card.html.erb
    <%= link_to ride_path(ride), class:"no-text-decoration text-black" do %>
      <div class="card-location mb-3 position-relative">
        <div class="position-absolute" style="background-color: #61d7efcb; border-radius: 0px 20px 20px 0px; width: 50px; bottom: 16px; left: 0px; z-index: +1;">
          <div class="me-5 mx-1"><%=humanized_money_with_symbol(ride.price)%></div>
        </div>
        <div class="btn-seats-ride d-flex position-absolute" style="bottom: 50px; left: 0; z-index: +1;">
            <i class="fa-solid fa-user icon-seats-ride"></i>
            <div><%=ride.seats%>/5</div>
        </div>
        <div class="d-flex">
          <div style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path ride.beach.photo.key %>);" class="img-ride-card">
          </div>
          <div style="width: 50%;" class="mt-3">

            <div class="d-flex justify-content-between">
              <div class="d-flex">
                <% if user_signed_in? && current_user.photo.attached? %>
                  <%= cl_image_tag ride.user.photo.key, style: "border-radius: 50%; height: 24px; width: 24px;" %>
                <% else %>
                  <%= image_tag "user.png", style: "border-radius: 50%; height: 24px; width: 24px;" %>
                <% end %>
                <h4 style="font-size: 16px;">Driver: <%= ride.user.first_name %></h4>
              </div>
            </div>
            <div class="d-flex mt-2">
              <p class="me-5 card-date"><i class="fa-solid fa-clock"></i> <%= ride.date_time.strftime("%H:%M")%></p>
            </div>
            <div class="d-flex justify-content-between">
              <div class="card-location-infos">
                <p><i class="fa-sharp fa-solid fa-location-dot" style="color: #61D8EF;"></i> <%= ride.address.match(/^[^,]+(?=,)/) %> </p>
                <p><i class="fa-sharp fa-solid fa-location-dot" style="color: #61D8EF;" ></i> <%= ride.beach.name %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    <%end%>

app/views/rides/beach.html.erb
<div style="position: relative;">
  <div class="show_rides d-flex align-items-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @beach.photo.key %>');">
    <div class="container d-flex justify-content-end">
        <%= render partial: "shared/heart_btn", locals: { beach: @beach } %>
    </div>
  </div>
</div>

<div style="background-color: #F2FDFF; border-radius: 20px 20px 0 0; position: relative; margin-top: 40px;">
  <div class="container-rides-index-card mx-3">
    <div><h1 class="text-center" style="padding-top: 16px; margin-bottom: 16px;">Rides to <%= @beach.name %></h1></div>
      <% @rides.each do |ride|%>
        <%= render "ride_card", ride: ride %>
      <%end%>
  </div>

</div>

app/views/rides/edit.html.erb
<div style="position: relative;">
  <div class="show_rides" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @ride.beach.photo.key %>);">
    <div class="container">
      <div style="padding-top: 50px;" class="title d-flex justify-content-center algin-items-center">
        <h1>Edit Ride</h1>
      </div>
    </div>
  </div>
</div>

<div style="background-color: #F2FDFF; border-radius: 20px 20px 0 0; position: relative; margin-top: -40px;">
  <div class="space-div"></div>
  <div class="mt-4 ride-new" style="border-radius: 20px">
    <%= simple_form_for @ride do |f| %>
      <%= f.association :beach, collection: Beach.order('name ASC'), label: false, prompt: "Beach" %>
      <%= f.input :date_time, as: :datetime, label: false %>
      <%= f.input :address, label: false,
        input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
        wrapper_html: {class: "map-search", data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"] } }
      %>
      <%= f.input :seats, collection: 1..5, label: false, prompt: "Seats" %>
      <%= f.input :price, label: false, placeholder: "Price (€)" %>
      <div class="d-flex justify-content-center">
        <%= f.submit class: "btn-blue" %>
      </div>
    <% end %>
  </div>
</div>

app/views/rides/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1527731149372-fae504a1185f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80);">
</div>

<div style="background-color: #F2FDFF; border-radius: 20px 20px 0 0;">
  <div class="container-rides-index-card mx-3">
    <% if @rides.empty? %>
      <div class="no-results">
        <h1 class="pb-5">No results found..</h1>
        <%= link_to "Try again", root_path, class:"btn-blue" %>
      </div>
    <% else %>
      <h1 class="text-center py-2">Searchresults</h1>
    <% @rides.each do |ride|%>
      <%= render "ride_card", ride: ride %>
      <%end%>
    <% end %>
  </div>
</div>

app/views/rides/location.html.erb
<div style="position: relative;">
  <div class="show_rides" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @location.photo.key %>');">
    <div class="container">
      <div style="padding-top: 50px;" class="title d-flex justify-content-center algin-items-center">
      </div>
    </div>
  </div>
</div>

<div style="background-color: #F2FDFF; border-radius: 20px 20px 0 0; position: relative; margin-top: -40px;">
  <div class="container">
    <div><h1 class="text-center" style="padding-top: 16px; margin-bottom: 16px;">Rides to <%= @location.name %></h1></div>
      <% @rides.each do |ride|%>
        <%= render "ride_card", ride: ride %>
      <%end%>
  </div>
</div>

app/views/rides/new.html.erb
<div style="position: relative;">
  <div class="show_rides" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1520116468816-95b69f847357?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80);">
    <div class="container">
      <div style="padding-top: 50px;" class="title d-flex justify-content-center algin-items-center">
        <h1>New Ride</h1>
      </div>
    </div>
  </div>
</div>
<div style="background-color: #F2FDFF; border-radius: 20px 20px 0 0; position: relative; margin-top: -18px;">
  <div class="space-div"></div>
  <div class="mt-4 ride-new">
    <%= simple_form_for [@ride] do |f|%>
      <%= f.association :beach, collection: Beach.order('name ASC'), label: false, prompt: "Beach" %>
      <%= f.input :date_time, as: :datetime, label: false %>
      <%= f.input :address, label: false,
        input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
        wrapper_html: {class: "map-search", data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"] } }
      %>
      <%= f.input :seats, collection: 1..5, label: false, prompt: "Seats" %>
      <%= f.input :price, label: false, placeholder: "Price (€)" %>
      <div class="d-flex justify-content-center">
        <%= f.submit class: "btn-blue" %>
      </div>
    <% end %>
  </div>
</div>

app/views/rides/show.html.erb
<div>
  <div style="position: relative;">
    <div class="show_rides" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @ride.beach.photo.key %>');">
      <div class="container">
        <div style="padding-top: 50px;" class="title d-flex justify-content-center algin-items-center">
          <h1 class=""><%= @ride.date_time.strftime("%A") %>, <br> <%= @ride.date_time.strftime("%B") %> <%= @ride.date_time.day %>th</h1>
        </div>
      </div>
    </div>
  </div>

  <div style="background-color: #F2FDFF; border-radius: 20px 20px 0 0; position: relative; margin-top: -40px;">

    <% if @ride.user == current_user %>
      <%# Ride hour and addresses %>
      <div class="d-flex justify-content-between">
        <div class="card-location-infos mx-3 mt-4">
          <div class="d-flex">
            <div>
              <p><strong><%= @ride.date_time.strftime("%H:%M") %></strong></p>
            </div>
            <div>
              <p class="mx-2"><i class="fa-sharp fa-solid fa-location-dot" style="color: #61D8EF;"></i></p>
            </div>
            <div>
              <p><%= @ride.address.match(/^[^,]+(?=,)/) %></p>
              <div style="font-size: 13px; margin-top: -15px;"><p> <%= @ride.city %> </p></div>
            </div>
          </div>
          <div class="d-flex">
            <div>
              <p><strong><%= @ride.date_time.hour + 1%>:<%= @ride.date_time.strftime("%M")%></strong></p>
            </div>
          <div><p class="mx-2"><i class="fa-sharp fa-solid fa-location-dot" style="color: #61D8EF;"></i></p></div>
            <div>
              <p><%= @ride.beach.name %></p>
              <div style="font-size: 13px; margin-top: -15px;"><p><%= @ride.beach.location.name %></p></div>
            </div>
          </div>
        </div>
      </div>

      <div>
        <hr style="border-width: 8px; border-color:#a9a6a6;">
      </div>

      <%# Driver Information %>
      <div class="container mt-3">
        <div>
          <h2>Driver: <%= @ride.user.first_name %></h2>
        </div>

        <div class="d-flex mt-3">
          <div>
            <% if @ride.user.photo.attached? %>
              <%= cl_image_tag @ride.user.photo.key, class: "rounded-circle rides-image" %>
            <% else %>
              <%= image_tag "user.png", class: "rounded-circle rides-image" %>
            <% end %>
          </div>
          <div class="ms-3" style="">
            <p>Hello, my name is <%= @ride.user.full_name  %>. Born and raised in Portugal and passionate about the waves of our coast.</p>
          </div>
        </div>
        <div class="d-flex mt-1">
          <div><i class="fa-solid fa-car"></i> <%= @ride.user.car  %></div>
          <div><p class="ps-3"><%=@ride.seats%>/5</p></div>
        </div>
      </div>

      <div>
        <hr style="border-width: 8px; border-color:#a9a6a6;">
      </div>

      <%# Ride details (Pets, smoking and stuff) + MAP%>
      <div>
        <div class="ride-details">
          <h2>Ride Details</h2>
        </div>
        <div class="mx-3 permission-ride">
          <div class="d-flex">
            <div>
              <i class="fa-solid fa-paw paw-icon me-3"></i>
            </div>
            <div>
              <p>pets allowed</p>
            </div>
          </div>
          <div class="d-flex">
            <div>
              <i class="fa-solid fa-ban-smoking me-3"></i>
            </div>
            <div>
              <p>smoking not allowed</p>
            </div>
          </div>
          <div class="d-flex">
            <div>
              <i class="fa-solid fa-chess-bishop me-3"></i>
            </div>
            <div>
              <p>2/5 boards</p>
            </div>
          </div>
        </div>

        <div class="container">
          <div style="width: 100%; height: 500px;" class="rounded-4 mt-1 mb-2"
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>

      </div>
      <hr style="border-width: 8px; border-color:#a9a6a6;">

      <%# Cancellation Policy %>
      <div class="container mt-3">
        <h2>Cancellation Policy</h2>
        <p><strong>Free cancellation 24 hours before pick up.</strong> Non-refundable for later cancellations.</p>
      </div>
      <hr style="border-width: 8px; border-color:#a9a6a6;">
      <%# Ground Rules %>
      <div class="container mt-3">
        <h2>Ground Rules</h2>
        <p>We ask every one to remember a few simple things about how have a harmonious ride:</p>
        <div class="d-flex align-items-center mb-2">
          <i class="fa-solid fa-thumbs-up me-2"></i>
          <p style="margin-bottom: 0;">Respect the driver and the other passengers</p>
        </div>
        <div class="d-flex align-items-center mb-2">
          <i class="fa-solid fa-thumbs-up me-2"></i>
          <p style="margin-bottom: 0;">Respect the drivers car</p>
        </div>
        <div class="d-flex align-items-center mb-2">
          <i class="fa-solid fa-thumbs-down me-2"></i>
          <p style="margin-bottom: 0;">Leave trash behind</p>
        </div>
      </div>
      <hr style="border-width: 8px; border-color:#a9a6a6;">
      <%# Conditions %>
      <div class="container mt-3">
        <p><em>By selecting the button bellow, I agree to the <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" target="_blank">TagAlong Booking & Refund Policies</a>, and that TagAlong can charge my payment method if I'm responsible for damage.</em></p>
      </div>

      <%# Edit btn %>
      <div class="d-flex justify-content-center mb-4">
        <div>
          <%= link_to "Edit", edit_ride_path(@ride), class:"btn-blue"%>
        </div>
      </div>

    <% else %>
      <%= simple_form_for [@ride, @booking], data: { controller: 'price-update' } do |f|%>
        <%# Ride hour and addresses %>
        <div class="d-flex justify-content-between">
          <div class="card-location-infos mx-3 mt-4">
            <div class="d-flex">
              <div>
                <p><strong><%= @ride.date_time.strftime("%H:%M") %></strong></p>
              </div>
              <div>
                <p class="mx-2"><i class="fa-sharp fa-solid fa-location-dot" style="color: #61D8EF;"></i></p>
              </div>
              <div>
                <p><%= @ride.address.match(/^[^,]+(?=,)/) %></p>
                <div style="font-size: 13px; margin-top: -15px;"><p> <%= @ride.city %> </p></div>
              </div>
            </div>
            <div class="d-flex">
              <div>
                <p><strong><%= @ride.date_time.hour + 1%>:<%= @ride.date_time.strftime("%M")%></strong></p>
              </div>
            <div><p class="mx-2"><i class="fa-sharp fa-solid fa-location-dot" style="color: #61D8EF;"></i></p></div>
              <div>
                <p><%= @ride.beach.name %></p>
                <div style="font-size: 13px; margin-top: -15px;"><p><%= @ride.beach.location.name %></p></div>
              </div>
            </div>
          </div>
        </div>

        <div>
          <hr style="border-width: 8px; border-color:#a9a6a6;">
        </div>

        <%# Ride price  %>
        <div class="container mt-3">
          <%= f.input :seats, collection: 1..3, prompt: "Seats", label: false, input_html: { data: { target: "price-update.seats" } }%>
        </div>
        <div class="container mt-3">
          <div class="d-flex justify-content-between align-items-center">
            <div>
              <p style="margin-bottom: 0;">Price per seat:</p>
            </div>
            <div>
              <div style="padding: 5px 10px;">
                <div data-price-update-target="price">
                  <%= humanized_money_with_symbol(@ride.price) %>
                </div>
              </div>
            </div>
          </div>
          <div class="d-flex justify-content-between align-items-center">
            <div>
              <h3 style="margin-bottom: 0;">Total:</h3>
            </div>
            <div>
              <div style="background-color: #61D8EF; border-radius: 35px; padding: 5px 10px;">
                <div data-price-update-target="totalPrice">
                  <%= humanized_money_with_symbol(@ride.price) %>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div>
          <hr style="border-width: 8px; border-color:#a9a6a6;">
        </div>

          <%# Driver information %>
        <div class="container mt-3">
          <div>
            <h2>Driver: <%= @ride.user.first_name %></h2>
          </div>

          <div class="d-flex mt-3">
            <div>
              <% if @ride.user.photo.attached? %>
                <%= cl_image_tag @ride.user.photo.key, class: "rounded-circle rides-image" %>
              <% else %>
                <%= image_tag "user.png", class: "rounded-circle rides-image" %>
              <% end %>
            </div>
            <div class="ms-3" style="">
              <p>Hello, my name is <%= @ride.user.full_name  %>. Born and raised in Portugal and passionate about the waves of our coast.</p>
            </div>
          </div>
          <div class="d-flex justify-content-between mt-1">
            <div><i class="fa-solid fa-car"></i> <%= @ride.user.car  %></div>
            <div>
              <%= link_to "Message #{@ride.user.first_name}", ride_chatrooms_path(@ride), data: { method: :post }, class:"btn-blue" %>
            </div>
          </div>
        </div>

        <div>
          <hr style="border-width: 8px; border-color:#a9a6a6;">
        </div>

          <%# Ride details (Pets, smoking and stuff) + MAP%>
        <div>
          <div class="ride-details">
            <h2>Ride Details</h2>
          </div>
          <div class="mx-3 permission-ride">
            <div class="d-flex">
              <div>
                <i class="fa-solid fa-paw paw-icon me-3"></i>
              </div>
              <div>
                <p>pets allowed</p>
              </div>
            </div>
            <div class="d-flex">
              <div>
                <i class="fa-solid fa-ban-smoking me-3"></i>
              </div>
              <div>
                <p>smoking not allowed</p>
              </div>
            </div>
            <div class="d-flex">
              <div>
                <i class="fa-solid fa-chess-bishop me-3"></i>
              </div>
              <div>
                <p>2/5 boards</p>
              </div>
            </div>
          </div>

          <div class="container">
            <div style="width: 100%; height: 500px;" class="rounded-4 mt-1 mb-2"
              data-controller="map"
              data-map-markers-value="<%= @markers.to_json %>"
              data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
            </div>
          </div>

        </div>
        <hr style="border-width: 8px; border-color:#a9a6a6;">

        <%# Add Cancellation Policy, Ground Rules and Conditions %>
        <%# Cancellation Policy %>
        <div class="container mt-3">
          <h2>Cancellation Policy</h2>
          <p><strong>Free cancellation 24 hours before pick up.</strong> Non-refundable for later cancellations.</p>
        </div>
        <hr style="border-width: 8px; border-color:#a9a6a6;">
        <%# Ground Rules %>
        <div class="container mt-3">
          <h2>Ground Rules</h2>
          <p>We ask every one to remember a few simple things about how have a harmonious ride:</p>
          <div class="d-flex align-items-center mb-2">
            <i class="fa-solid fa-thumbs-up me-2"></i>
            <p style="margin-bottom: 0;">Respect the driver and the other passengers</p>
          </div>
          <div class="d-flex align-items-center mb-2">
            <i class="fa-solid fa-thumbs-up me-2"></i>
            <p style="margin-bottom: 0;">Respect the drivers car</p>
          </div>
          <div class="d-flex align-items-center mb-2">
            <i class="fa-solid fa-thumbs-down me-2"></i>
            <p style="margin-bottom: 0;">Leave trash behind</p>
          </div>
        </div>
        <hr style="border-width: 8px; border-color:#a9a6a6;">
        <%# Conditions %>
        <div class="container mt-3">
          <p><em>By selecting the button bellow, I agree to the <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" target="_blank">TagAlong Booking & Refund Policies</a>, and that TagAlong can charge my payment method if I'm responsible for damage.</em></p>
        </div>
        <%# Booking/ Editing button !!!DONE!!!%>

        <div class="d-flex justify-content-center my-3">
          <%= f.submit "Book now", class:"btn-blue"%>
        </div>
      <% end %>
    <% end %>
  </div>


</div>

<%# Create alternative for the owner of the Ride %>

<%#
<div class="bk-nw-bx" style="position:fixed; bottom: 0; width: 100%;">
  <% if current_user == @ride.user %>
    <%# <%= link_to "Edit", edit_ride_path, class:"btn-blue btn-book" %>
  <%# <% else %>
    <%# <%= link_to "Book", new_ride_booking_path(@ride), class:"btn-blue btn-book" %>
  <%# <% end %>
<%# </div>
%>